language: cpp
python: 3.6
compiler:
  - gcc

before_script:
  # Spams log, suppress output during build of boost, around 20 mins
  - python ./GetLibsI.py boost gnump gtest

script:
  # For now just cpp tests,
  - cd cpp && bash ./build.sh clean travis
