language: cpp
python: 2.7
compiler:
  - gcc

before_script:
  # Spams log, suppress output during build of boost, around 20 mins
  - bash ./bootstrap.sh

script:
  # For now just cpp tests,
  - cd cpp && bash ./build.sh clean travis
