language: cpp
compiler: 
  - gcc

before_script:
  - sudo apt-get update -y
  - aptitude search boost
  - ./GetLibsI.py gtest

script:
  # For now just cpp tests, retry
  #- ./cpp/build.sh clean test
